config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :profile, :as => :profiles
  
  post '/whole_food', to: 'whole_food#create'
  delete '/whole_food', to: 'whole_food#delete'

  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_many :whole_foods
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/whole_food.rb
class WholeFood < ApplicationRecord
    belongs_to :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    protect_from_forgery unless: -> { request.format.json? }
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :first_name, :last_name, :password, :password_confirmation, :current_password)}
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :first_name, :last_name, :password, :password_confirmation, :current_password)}
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!

  def index
  end
  
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      flash[:success] = "Profile created."
      redirect_to(profile_path(@profile))
    else
      flash[:error] = "Profile not created."
      render ('new')
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      flash[:success] = "Profile updated."
      redirect_to(profile_path(@profile))
    else
      flash[:error] = "Profile update failed."
      render('edit')
    end
  end

  private 

  def profile_params
    params.require(:profile).permit(
      :first_name,
      :last_name,
      :weight,
      :height,
      :gender,
      :activity,
      :user_id
    )
  end

end

app/controllers/whole_food_controller.rb
class WholeFoodController < ApplicationController

    def create
      @whole_food = WholeFood.new(whole_food_params)
      if @whole_food.save
        flash[:success] = "Food saved."
        redirect_to(root_path)
      else
        flash[:error] = "WWWhoops."
        render ('new')
      end
    end

    def delete
      @whole_food = WholeFood.find(params[:id])
      if @whole_food.destroy()
        flash[:success] = "Food deleted."
        redirect_to(root_path)
      else
        flash[:error] = "WWWhoops."
        render ('new')
      end
    end

    private 

    def whole_food_params
      params.require(:whole_food).permit(
        :name,
        :fdcid,
        :profile_id
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
      end
    
      def resource
        @resource ||= User.new
      end
    
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/whole_food_helper.rb
module WholeFoodHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

    <% if current_user.profile %>



        <input id="profile-id" name="profile-id" type="hidden" value="<%= current_user.profile.id %>">

        <main id="app"></main>

        <script>
        var event = new Event('loggedIn');
        document.dispatchEvent(event);
        </script>
        
    <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vitrak</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <div>&nbsp;</div>
      <h1><%= link_to(root_path) do %>VITRAK<% end %><br></h1>
      <% if user_signed_in? %>
      <p>
        <% if user_signed_in? %>
          <!--<strong><%= current_user.email %></strong><br />-->
          <strong><%= current_user.profile.first_name %></strong><br />
          <!--<%= link_to "Edit account info", edit_user_registration_path %><br />-->

          <% if current_user.profile %>
            <%= link_to("View profile", profile_path(current_user.profile)) %><br />
          <% else %>
            <%= link_to("Create profile", new_profile_path) %><br />
          <% end %>

          <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
        <% else %>
          <!-- 
          <%= link_to "Sign up", new_user_registration_path %><br />
          <%= link_to "Login", new_user_session_path %><br />
          -->
        <% end %>
      </p>
      <% end %>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>